Custom tags
leafchild0/chart-desk pull request #60
Opened 2022-04-21 15:04 UTC by proteus1121

api for creating and assigning tags

TODO: need to mix keywords and custom tags.

2022-04-29 09:39 UTC, proteus1121 commented on ui/src/components/FilterableTable.vue
> +	import Vue from 'vue';
@leafchild0 maybe should be a better place for it, but not sure where?

2022-05-01 15:51 UTC, leafchild0 requested changes

2022-05-01 15:51 UTC, leafchild0 commented on charts/src/main/java/chart/desk/controllers/TagsController.java
> +    @PostMapping("/{tagId}/assign")
Good naming

2022-05-01 15:51 UTC, leafchild0 commented on charts/src/main/java/chart/desk/model/db/ChartModel.java
> +        // TODO: move keywords in tags table
When do you plan to do it?

2022-05-01 15:51 UTC, leafchild0 commented on charts/src/main/java/chart/desk/model/db/TagModel.java
> +        this.created = new Date();
Is there a need to set this date manually? Why no use annotation?

2022-05-01 15:51 UTC, leafchild0 commented on charts/src/main/java/chart/desk/services/ChartService.java
> +    @Transactional
Why this is needed?

2022-05-01 15:51 UTC, leafchild0 commented on charts/src/main/java/chart/desk/services/ChartService.java
>          return chartRepository.save(new ChartModel(chartEntry, digestHex, urls, userName, source));
Reuse new method here

2022-05-01 15:51 UTC, leafchild0 commented on charts/src/main/java/chart/desk/services/ChartService.java
> +    @Transactional
Hm, transaction on get methods looks suspicious

2022-05-01 15:51 UTC, leafchild0 commented on ui/src/components/ChartsDetails.vue
> +			onTagAdded(tag, chartName) {
Good

2022-05-01 15:51 UTC, leafchild0 commented on ui/src/components/FilterableTable.vue
> +	import Vue from 'vue';
You can use it in a different way. This is a global registration, but you can also use it locally, for this component only. Docs: https://vuejs.org/v2/guide/components-registration.html.
Basically just import it and pass into components array for this component

2022-05-01 15:51 UTC, leafchild0 commented on ui/src/components/ChartsDetails.vue
> +			onTagAdded(tag, chartName) {
The only suggestion I have:
 noticed it's duplicated in 2 places, which looks like a candidate for a component that needs to be used in 2 places

2022-05-03 11:21 UTC, proteus1121 commented on ui/src/components/FilterableTable.vue
> +	import Vue from 'vue';
ok, done

2022-05-03 11:21 UTC, proteus1121 commented on charts/src/main/java/chart/desk/model/db/ChartModel.java
> +        // TODO: move keywords in tags table
already done, forget to remove todo

2022-05-03 11:22 UTC, proteus1121 commented on charts/src/main/java/chart/desk/model/db/TagModel.java
> +        this.created = new Date();
ok, lets use annotation

2022-05-03 11:23 UTC, proteus1121 commented on charts/src/main/java/chart/desk/services/ChartService.java
> +    @Transactional
because when you want to fetch chart model with joined tag entity you need to use transactional annotations, otherwise you will get an exception

2022-05-04 05:35 UTC, leafchild0 commented on charts/src/main/java/chart/desk/services/ChartService.java
> +    @Transactional
Got it, can you move transactional to class then?

2022-05-04 14:18 UTC, proteus1121 commented on ui/src/components/ChartsDetails.vue
> +			onTagAdded(tag, chartName) {
done https://github.com/leafchild0/chart-desk/pull/60/commits/f1c786184af07d134a6ce91f5d0c86d6de73d3b8

2022-05-04 19:35 UTC, leafchild0 approved these changes

2022-05-05 07:59 UTC, merged